export const ADD_NEW_PARENT_NOTE_TO_LIST = 'ADD_NEW_PARENT_NOTE_TO_LIST';
export const DELETE_PARENT_NOTE = 'DELETE_PARENT_NOTE';
export const EDIT_PARENT_NOTE = 'EDIT_PARENT_NOTE';
export const LOAD_USER_FROM_DATABASE = 'LOAD_USER_FROM_DATABASE';